server:
  port: 8082

provider:
  login: "admin"
  password: "password"
  url: "https://localhost:8080"


spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: default-route
          uri: ${provider.url}
          predicates:
            - Path=/**
          filters:
            - ConnectorProxyFilter

