server:
  port: 8082

provider:
  login: "admin"
  password: "password"
  url: "https://localhost:8080"

zuul:
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000
  routes:
    ids-connector-provider:
      path: /connector/**
      url: ${provider.url}/
